#! /usr/bin/python
import sys
import os

os.mkdir('build')
os.mkdir('include')
os.mkdir('src')
fh = open('CMakeLists.txt','w')

fh.write("cmake_minimum_required(VERSION 2.6)\n")

fh.write("project(NAME_THIS_PROJECT)\n\n")

fh.write('set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -g -Wall -fcolor-diagnostics)" \n\n')

fh.write("set( MY_INCLUDES ${PROJECT_SRC_DIR}/include) \n")

fh.write("set( MY_SOURCES src/main.cpp) \n")
fh.write("add_executable(NAME_THIS_PROJECT ${MY_SOURCES})\n")

